name             'bootstrap_linux'
maintainer       'Levi Smith'
maintainer_email 'levi@fynx.me'
license          'MIT'
description      'Installs/Configures bootstrap_linux'
long_description 'Installs/Configures bootstrap_linux'
version          '0.1.0'
